# Generated by Django 2.1.7 on 2019-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='devices',
            field=models.CharField(max_length=100),
        ),
    ]
