# Generated by Django 2.1.7 on 2019-05-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='device',
        ),
    ]
