# Generated by Django 2.1.7 on 2019-04-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='device',
            new_name='devices',
        ),
    ]
