# Generated by Django 2.1.7 on 2019-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190418_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_ip_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
