# Generated by Django 2.1.7 on 2019-05-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_data_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapp.devices'),
            preserve_default=False,
        ),
    ]
