# Generated by Django 2.1.7 on 2019-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_devices_device_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='device_ip_address',
            new_name='local_ip',
        ),
        migrations.AddField(
            model_name='devices',
            name='mac_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
