# Generated by Django 2.1.7 on 2019-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190428_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_id',
            field=models.IntegerField(null=True),
        ),
    ]
