# Generated by Django 2.1.7 on 2019-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='values',
            field=models.FileField(blank=True, null=True, upload_to='data/%Y/%m/%d/'),
        ),
    ]
