# Generated by Django 2.1.7 on 2019-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_data_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='values',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
