# Generated by Django 2.1.7 on 2019-04-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190430_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_time',
            field=models.DateTimeField(null=True),
        ),
    ]
