# Generated by Django 2.1.7 on 2019-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190430_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
