# Generated by Django 2.1.7 on 2019-04-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190501_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data_time',
            new_name='created_date',
        ),
    ]
