# Generated by Django 2.1.7 on 2019-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20190501_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='id',
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
