# Generated by Django 2.1.7 on 2019-05-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20190503_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device_id',
        ),
        migrations.AddField(
            model_name='devices',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
