# Generated by Django 2.1.7 on 2019-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20190503_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
