# Generated by Django 2.1.7 on 2019-05-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20190516_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
