# Generated by Django 2.1.7 on 2019-05-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20190518_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
